### ISSUE TITLE
AssertionError:   assert 0 < size <= self._size 

### ISSUE THREAD

**Issue by TechnoX** [LoyVanBeek/vizbox#13]
Dunno if its related with issue #12 but this is another error I get sometimes: 

```

[ERROR] [1529241039.337274]: bad callback: <function callback at 0x7f50d0121aa0>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/fredrik/home_ws/src/vizbox/backendbase.py", line 5, in callback
    cb(converted)
  File "/home/fredrik/home_ws/src/vizbox/server.py", line 91, in handle_challenge_step
    self.write_message(data)
  File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 256, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 801, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 780, in _write_frame
    return self.stream.write(frame)
  File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 540, in write
    self._handle_write()
  File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 1009, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 183, in advance
    assert 0 < size <= self._size
AssertionError

```

**Comment by tom-seasalt** [comment]
Maybe[ #2871](https://github.com/tornadoweb/tornado/issues/2871) can help.
